### ISSUE TITLE
Socket hangup using remote Redis server

### ISSUE THREAD

**Issue by selfagency** [smrchy/rsmq#100]
I created a [serverless interface for RSMQ using Now.sh](https://gitlab.com/selfagency/now-rsmq). Everything works fine in development when I use a local Redis server. But as soon as I try using a remote Redis server, I start getting socket hangup errors.

```
Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at Socket.socketOnEnd (_http_client.js:426:23)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I've tried two different remote connections, both of which I'm able to connect to from my local machine using a Redis client, so the issue isn't that the connection is being rejected.

Any ideas?

**Comment by selfagency** [comment]
After further debugging, it looks like the problem is with Now and not RSMQ.
