### ISSUE TITLE
ReplyError: ERR Error running script (Windows)

### ISSUE THREAD

**Issue by mrspartak** [smrchy/rsmq#115]
Code 
```js
var [err, id] = await __.to( rsmq.sendMessageAsync({ qname: 'test', message: 'test' }) )
console.log('sendMessageAsync', err ? err.message : '-', id)

var [err, message] = await __.to( rsmq.receiveMessageAsync({ qname: 'test' }) )
console.log('receiveMessageAsync', err, message)
```

Getting an error while receiveMessageAsync
```js
receiveMessageAsync ReplyError: ERR Error running script (call to f_937bb26841b123886255ef3956a57c83e829ab3e): @user_script:
1: ERR min or max is not a float
    at parseError (E:\OpenServer\OSPanel\domains\todoforme\backend\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (E:\OpenServer\OSPanel\domains\todoforme\backend\node_modules\redis-parser\lib\parser.js:302:14) {
  command: 'EVALSHA',
  args: [
    '937bb26841b123886255ef3956a57c83e829ab3e',
    3,
    'todoforme:rsmq:test',
    1584283308608,
    1584283338608
  ],
  code: 'ERR'
} undefined

```

**Comment by adlanarifzr** [comment]
I have same issue. Any solution?
