### ISSUE TITLE
ReplyError: ERR unknown command 'time'

### ISSUE THREAD

**Issue by irvingswiftj** [smrchy/rsmq#36]
I'm getting the following error going on forever!

ReplyError: ERR unknown command 'time'
    at parseError (/myproject/socket-server/node_modules/redis-parser/lib/parser.js:163:12)
    at parseType (/myproject/socket-server/node_modules/redis-parser/lib/parser.js:224:14)

**Comment by irvingswiftj** [comment]
sorry, this is rsmq-worker issue it seems
